### PR TITLE
Major build updates

### LINKED ISSUE #250: Update *SdkVersion to 33
Starting November, Google will require the targetSdkVersion to be >= 31, otherwise app updates will be rejected.
https://developer.android.com/google/play/requirements/target-sdk

We could probably think about increasing the minSdkVersion.

### PR DESCRIPTION
**Pull request by cyb3rko**
Updated all dependencies, gradle versions and sdk levels.
Except all swagger implementations, I haven't touched these.

Closes #250

### CODE REVIEW

**Comment by cyb3rko** [comment]
Ah, you need Java 11 now.

**Comment by cyb3rko** [comment]
I'll update the build file, the GitHub workflow has to be updated then.

**Comment by jmattheis** [comment]
Could you update the workflow? You probably have to change version here https://github.com/gotify/android/blob/master/.github/workflows/main.yml#L13

**Review by jmattheis — APPROVED** [review]
Awesome! Sorry for the review delay.

I've rebased the branch to remove the merge commit and renamed my wip commit to something more expressive.

**Pull request merged**
